<?xml version="1.0" encoding="utf-8"?><Database Name="CAFEMANAGEMENT" Class="CMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=CAFEMANAGEMENT;Integrated Security=True" SettingsObjectName="CM.DAL.Properties.Settings" SettingsPropertyName="CAFEMANAGEMENTConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="ACCOUNT_ACCOUNT_IMAGE" Member="ACCOUNT_IMAGE" ThisKey="Id" OtherKey="Id" Type="ACCOUNT_IMAGE" Cardinality="One" />
      <Association Name="EMPLOYEE_ACCOUNT" Member="EMPLOYEE" ThisKey="EmployeeId" OtherKey="Id" Type="EMPLOYEE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BILL" Member="BILLs">
    <Type Name="BILL">
      <Column Name="Id" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="BILL_PRODUCT_BILL" Member="PRODUCT_BILLs" ThisKey="Id" OtherKey="BillId" Type="PRODUCT_BILL" />
      <Association Name="CUSTOMER_BILL" Member="CUSTOMER" ThisKey="CustomerId" OtherKey="Id" Type="CUSTOMER" IsForeignKey="true" />
      <Association Name="EMPLOYEE_BILL" Member="EMPLOYEE" ThisKey="EmployeeId" OtherKey="Id" Type="EMPLOYEE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CUSTOMER_BILL" Member="BILLs" ThisKey="Id" OtherKey="CustomerId" Type="BILL" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Daystart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="EMPLOYEE_ACCOUNT" Member="ACCOUNTs" ThisKey="Id" OtherKey="EmployeeId" Type="ACCOUNT" />
      <Association Name="EMPLOYEE_BILL" Member="BILLs" ThisKey="Id" OtherKey="EmployeeId" Type="BILL" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsTopping" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PRODUCT_PRODUCT_BILL" Member="PRODUCT_BILLs" ThisKey="Id" OtherKey="ProductId" Type="PRODUCT_BILL" />
      <Association Name="PRODUCTTYPE_PRODUCT" Member="PRODUCTTYPE" ThisKey="ProductId" OtherKey="Id" Type="PRODUCTTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT_BILL" Member="PRODUCT_BILLs">
    <Type Name="PRODUCT_BILL">
      <Column Name="BillId" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BILL_PRODUCT_BILL" Member="BILL" ThisKey="BillId" OtherKey="Id" Type="BILL" IsForeignKey="true" />
      <Association Name="PRODUCT_PRODUCT_BILL" Member="PRODUCT" ThisKey="ProductId" OtherKey="Id" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTTYPE" Member="PRODUCTTYPEs">
    <Type Name="PRODUCTTYPE">
      <Column Name="Id" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="PRODUCTTYPE_PRODUCT" Member="PRODUCTs" ThisKey="Id" OtherKey="ProductId" Type="PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.ACCOUNT_IMAGE" Member="ACCOUNT_IMAGEs">
    <Type Name="ACCOUNT_IMAGE">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Img" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ACCOUNT_ACCOUNT_IMAGE" Member="ACCOUNT" ThisKey="Id" OtherKey="Id" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>