CREATE DATABASE COFFEEMANAGEMENT

GO 

USE COFFEEMANAGEMENT


CREATE TABLE CUSTOMERS
(
	CUSTOMERID CHAR(4) PRIMARY KEY ,
	PHONENUMBER VARCHAR(20),
	DATEREGISTER SMALLDATETIME,
	TOTALSPEND MONEY
)


CREATE TABLE EMPLOYEES
(
	EMPLOYEEID CHAR(4) PRIMARY KEY,
	NAME VARCHAR(40),
	PHONE VARCHAR(20),
	DATESTART SMALLDATETIME,
	
)

CREATE TABLE BILLS 
(
	BILLID CHAR(4) PRIMARY KEY ,
	DATECREATE DATE,
	VALUE MONEY,
	CUSTOMERID CHAR(4) ,
	EMPLOYEEID CHAR(4)
)



CREATE TABLE PRODUCTS
(
	PRODUCTID CHAR(4) PRIMARY KEY ,
	NAME VARCHAR(50),
	TYPEPRODUCT VARCHAR(20),
	PRICEPRODUCT MONEY,
	EXP DATE,
	MFG DATE,
)

CREATE TABLE BILLDETAILS
(
	BILLID CHAR(4),
	PRODUCTID CHAR(4),
	NUMBER INTEGER,
	PRICEBILL MONEY,
	CONSTRAINT PK_BILLDETAILS PRIMARY KEY(BILLID,PRODUCTID),
)



ALTER TABLE BILLS
ADD CONSTRAINT FK_BILLS_CUSTOMERS FOREIGN KEY(CUSTOMERID)
REFERENCES dbo.CUSTOMERS(CUSTOMERID)

ALTER TABLE BILLS
ADD CONSTRAINT FK_BILLS_EMPLOYEES FOREIGN KEY(EMPLOYEEID)
REFERENCES dbo.EMPLOYEES(EMPLOYEEID)


ALTER TABLE dbo.BILLDETAILS
ADD CONSTRAINT FK_BILLDETAILS_PRODUCTS FOREIGN KEY(PRODUCTID)
REFERENCES dbo.PRODUCTS(PRODUCTID)

ALTER TABLE dbo.BILLDETAILS
ADD CONSTRAINT FK_BILLDETAILS_BILLS FOREIGN KEY(BILLID)
REFERENCES dbo.BILLS(BILLID)